{{- if .Values.wazuh.enabled }}
{{- if not .Values.wazuh.apiCred.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-api-cred
  namespace: {{ .Release.Namespace }}
data:
  API_USERNAME: {{ .Values.wazuh.apiCred.username | default (randAlphaNum 10) | b64enc }}
  API_PASSWORD: {{ .Values.wazuh.apiCred.password | default (printf "%s%s%s!%s" (randAlpha 1 | upper) (randAlpha 1 | lower) (randNumeric 1) (randAlphaNum 13)) | b64enc | quote }}
{{- end }}
{{- end }}